- name: Install PIP on RedHat
  yum: name=python-pip state=latest
  when: ansible_os_family == "RedHat"

- name: Install PIP on Debian
  apt: name=python-pip state=latest
  when: ansible_os_family == "Debian"

- name: Install BOTO 
  pip: name=boto

- name: Create tower install tower install directory
  file: path={{tower_install_location}} state=directory

- name: Download tower installer version {{ tower_version }} from S3
  s3: bucket={{ tower_s3_bucket }} object={{ tower_s3_object }} dest={{tower_install_location}}/tower_installer-{{tower_version}}.tar mode=get

- name: Extract tower installer
  unarchive: src={{tower_install_location}}/tower_installer-{{tower_version}}.tar dest={{tower_install_location}}/tower-{{tower_version}}